//Code is generated by ucloud code generator, don't modify it by hand, it will cause undefined behaviors.
//go:generate ucloud-gen-go-api UDataArk DescribeUhostTmMeta

package udataark

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

type DeleteUserVDiskSnapshotRequest struct {
	request.CommonBase

	// 盘id
	VDiskId *string `required:"true"`

	// 快照id
	SnapshotId *string `required:"true"`

	// 盘的版本
	Version int
}

type DeleteUserVDiskSnapshotResponse struct {
	response.CommonBase

}

func (c *UDataArkClient) NewDeleteUserVDiskSnapshotRequest() *DeleteUserVDiskSnapshotRequest {
	req := &DeleteUserVDiskSnapshotRequest{}
	c.Client.SetupRequest(req)
	return req
}

func (c *UDataArkClient) CreateDeleteUserVDiskSnapshotRequest(req *DeleteUserVDiskSnapshotRequest) (*DeleteUserVDiskSnapshotResponse, error) {
	var err error
	var res DeleteUserVDiskSnapshotResponse

	err = c.Client.InvokeAction("DeleteUserVDiskSnapshot", req, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
