//Code is generated by ucloud code generator, don't modify it by hand, it will cause undefined behaviors.
//go:generate ucloud-gen-go-api UDataArk DescribeUhostTmMeta

package udataark

import (
	"github.com/ucloud/ucloud-sdk-go/ucloud/request"
	"github.com/ucloud/ucloud-sdk-go/ucloud/response"
)

type RollbackPoint struct {
	DiskId string;
	RestoreTimestamp int;
	RestoreId string;
	UserManual string;
}

type RestoreUhostDiskRequest struct {
	request.CommonBase

	// uhostId
	UHostId *string `required:"true"`

	// 恢复盘的信息
	RestoreDiskSet []RollbackPoint
}

type RestoreUhostDiskResponse struct {
	response.CommonBase
}

func (c *UDataArkClient) NewRestoreUhostDiskRequest() *RestoreUhostDiskRequest {
	req := &RestoreUhostDiskRequest{}
	c.Client.SetupRequest(req)
	return req
}

func (c *UDataArkClient) RestoreUhostDisk(req *RestoreUhostDiskRequest) (*RestoreUhostDiskResponse, error) {
	var err error
	var res RestoreUhostDiskResponse

	err = c.Client.InvokeAction("RestoreUHostDisk", req, &res)
	if err != nil {
		return &res, err
	}

	return &res, nil
}
